name: "Build tests"
on:
  push:
    branches: [ main ]
jobs:
  linux_test_job:
    runs-on: ubuntu-latest
    name: "Linux test"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build
      - run: npm link && sc2ktojson -v
  mac_test_job:
    runs-on: macos-latest
    name: macOS test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build
      - run: npm link && sc2ktojson -v
  win_test_job:
    runs-on: windows-latest
    name: Windows test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build
      - run: npm link && sc2ktojson -v
